[package]
name = "reader"
version = "0.1.0"
authors = ["sanjeyac <sanjeyac>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
svg = "0.5.12"
csv = "1.1"
clap = "2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
